- name: Aquire root password (generate or use one from /etc/trinity/passwords)
  set_fact:
    mysql_root_pwd: "{{ lookup('password',
                          '/trinity/local/passwords/mysql/root.txt  
                           chars=ascii_letters,digits,hexdigits') }}"

- name: Install MariaDB packages
  yum:
   name: "{{ item }}"
   state: installed
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python

- name: Start MariaDB
  systemd:
    name: mariadb.service
    state: started
    enabled: yes

- name: Set MariaDB's root pasword
  mysql_user: 
    config_file: "/root/.my.cnf"
    name: root
    password: "{{ mysql_root_pwd }}"
    host_all: yes
    check_implicit_admin: yes
    state: present

- name: Create /root/.my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
    backup: yes

- name: Remove anonymous users
  mysql_user:
    config_file: "/root/.my.cnf"
    name: ""
    host_all: yes
    state: absent

- name: Remove test db
  mysql_db:
    config_file: "/root/.my.cnf"
    name: test
    state: absent
