- name: Aquire root password (generate or use one from /etc/trinity/passwords)
  set_fact:
    mysql_root_pwd: "{{ lookup('password',
                          '/etc/trinity/passwords/mysql/root.txt  
                           chars=ascii_letters,digits,hexdigits') }}"

- name: Install MariaDB packages
  yum:
   name: "{{ item }}"
   state: installed
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python

- name: Get /var/lib/mysql status
  stat:
    path: "/var/lib/mysql"
  register: file_var_lib_mysql

- name: Get /trinity/local/var/lib/mysql status
  stat:
    path: "{{ trix_path_local }}/var/lib/mysql"
  register: file_trix_local_var_lib_mysql

- name: Creates /trinity/local/var/lib
  file:
    path: "{{ trix_path_local }}/var/lib"
    state: directory
  when: file_trix_local_var_lib_mysql.stat.exists == False

- name: Move /var/lib/mysql to /trinity/local dir
  command: /usr/bin/mv /var/lib/mysql "{{ trix_path_local }}/var/lib/"
  when: file_var_lib_mysql.stat.exists == True and file_var_lib_mysql.stat.isdir == True and file_trix_local_var_lib_mysql.stat.exists == False

- name: Render /etc/my.cnf
  template:
    src: "etc_my.cnf.j2"
    dest: "/etc/my.cnf"
    backup: yes

- name: Start MariaDB
  systemd:
    name: mariadb.service
    state: started
    enabled: yes

- name: Set MariaDB's root pasword
  mysql_user: 
    config_file: "/root/.my.cnf"
    name: root
    password: "{{ mysql_root_pwd }}"
    host_all: yes
    check_implicit_admin: yes
    state: present

- name: Create /root/.my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
    backup: yes

- name: Remove anonymous users
  mysql_user:
    config_file: "/root/.my.cnf"
    name: ""
    host_all: yes
    state: absent

- name: Remove test db
  mysql_db:
    config_file: "/root/.my.cnf"
    name: test
    state: absent
